version: "3"
services:
  frontend:
    image: node:14
    volumes:
      - ./Frontend:/app
    working_dir: /app
    command: ["sh", "-c", "yarn && yarn start"]
    ports:
      - "3000:3000"
  backend:
    build: ./Backend
    ports:
      - "8000:8000"